Repository GenomicDataInfrastructure/standard-operating-procedures, pull requests merged in 2024-10, with the labels that each got.

#29 ZH-253
  CHANGELOG.md
  docs/GDI-SOP_information-service-management.md
  docs/images/GDI-ISM_schema.svg
  docs/images/GDI-ISM_schema_Node_Instance.svg
Labels: documentation

#37 Doc updates
  CONTRIBUTING.md
  README.md
  docs/GDI-SOP_style-guide.md
Labels: documentation

#31 ZH-266 - Addition of ORR document
  CHANGELOG.md
  README.md
  docs/GDI-SOP_charter.md
  docs/GDI-SOP_organisational-roles-and-responsibilities.md
Labels: documentation

#34 ZH-252 - 1+MG DAC Recommendation Approval Process
  CHANGELOG.md
  sops/README.md
  sops/european-level/GDI-SOP0003_SOP-1+MG-DAC-Recommendation-Approval.md
Labels: documentation

#35 ZH-350 - Create automatic SOP review reminders
  .github/workflows/review_reminder.yml
  CHANGELOG.md
  requirements.txt
  scripts/check_sop_reviews.py
  scripts/utils.py
Labels: enhancement

#44 update-changelog - Update CHANGELOG to v1.0.0
  CHANGELOG.md
Labels: documentation

#45 update-changelog - Remove duplicates
  CHANGELOG.md
Labels: bug
